### ISSUE TITLE
reporting -  marking aparece em branco (tem que passar o mouse)

### ISSUE THREAD

**Issue by gabrielabonicio** [camino-school/lanttern#75]
marking aparece em branco (tem que passar o mouse)

**Comment by endoooo** [comment]
![Image](https://github.com/camino-school/lanttern/assets/746889/f3e6c2f5-1e44-4c30-868d-9b86ab334b12)

**Comment by endoooo** [comment]
@gabrielabonicio can you check if it's fixed? (you can reopen the issue if it's not)

**Comment by gabrielabonicio** [comment]
looks the same to me, even after refreshing

**Comment by endoooo** [comment]
closed by #92
