### ISSUE TITLE
reporting -  conseguimos ordenar os estudantes 1) por turma e 2) em ordem alfabética?

### ISSUE THREAD

**Issue by gabrielabonicio** [camino-school/lanttern#76]
conseguimos ordenar os estudantes 1) por turma e 2) em ordem alfabética?

**Comment by endoooo** [comment]
order students lists by class and add class info in

- [ ] strand - reporting tab
- [ ] strand - assessments tab
- [ ] moment - assessments tab
- [ ] report card - students tab
- [ ] report card - grades tab
