### ISSUE TITLE
reporting - tag do que é Understanding e do que é Skill

### ISSUE THREAD

**Issue by gabrielabonicio** [camino-school/lanttern#77]
Tag do que é Understanding e do que é Skill

**Comment by endoooo** [comment]
- [ ] adjust curriculum visualization in strand assessment tab
- [ ] adjust curriculum visualization in strand reporting tab
- [ ] adjust curriculum visualization in moment assessment tab
- [ ] adjust assessment point name field requirement. it should be required in the context of moment (potentially more than one assessment point for the same curriculum item in the same moment), but not when used as strand goal
